### ISSUE TITLE
Poor clip playback performance

### ISSUE THREAD

**Issue by KuyaA** [teklynk/twitch_shoutout#1]
I was using the overlay with the following settings:
https://i.imgur.com/n8hfEAk.png
The chat message gets posted, the message, and the clip shows up in the OBS browser source.
However, when the clips are pulled the video playback only plays 2 frames while the audio playback is completely normal.

**Comment by teklynk** [comment]
Hmm, I have never seen this issue. One thing you can do is try setting the browser source FPS from 30 to 60. Also, try using Twitch.guru shout-out player to see if you have same issue.

**Comment by KuyaA** [comment]
It was a OBS setting. I had to enable browser source hardware acceleration. Ty for the reply!
