### ISSUE TITLE
watchclip stuck on the same clip

### ISSUE THREAD

**Issue by L-W-123** [teklynk/twitch_shoutout#11]
Recently the !watchclip command has become "stuck" on a specific clip for me. No matter how many new clips have been posted to chat it always plays the same one.

**Comment by teklynk** [comment]
Currently, The !watchclip command only works on clips that have a URL like: https://clips.twitch.tv/... This url comes from clips that were created using the clips maker. Right after a user creates a clip, they get a https://clips.twitch.tv link to copy and share. This link is different than the clips urls found on your channel. Example: https://www.twitch.tv/retroislandgaming/clip/LaconicCulturedPieMingLee-qxlzFZb89ZlEgdzP

I will look into making this work with other links like: https://www.twitch.tv/retroislandgaming/clip/LaconicCulturedPieMingLee-qxlzFZb89ZlEgdzP

**Comment by L-W-123** [comment]
Sorry if I wasn't clear enough. Up until recently it was working flawlessly, I already know that only that link format works. 
But even if I post a link with this format to the chat it still "stuck" and only plays a certain clip from a couple days ago.

**Comment by teklynk** [comment]
Thanks. I see the issue now. I did push out a change a few days ago which seems to have broken the !watchclip feature. I am looking into it now and will have a fix in place soon. I will keep you posted.

**Comment by teklynk** [comment]
This should be fixed now. You may need to refresh the browser source in OBS. Please test this to verify. 
Right click to open the browser source properties. Scroll to the bottom and you should see Reload and Clear browser cache button.

**Comment by L-W-123** [comment]
Yeah, it works again. Thanks for the quick fix.
