### ISSUE TITLE
Suddenly not working at all [not working again]

### ISSUE THREAD

**Issue by OGNetheri** [teklynk/twitch_shoutout#12]
As topic states. Today wanted to give shoutouts on stream but !so username, !so @username or so username didn't work at all. Tried to refresh source but no help.

Edit: I had to do whole thing again to be copypasted to get it working. Would it be possible for the settings site to have login so that one's settings would be saved if the whole thing needs to be "refreshed"?

**Comment by teklynk** [comment]
The web browser saves some settings for when you revisit the site. In order to have a login with accounts and settings for each user, It would require a database to store all of that. This is something that I do not want to do as it will then become a "Service" that I would have to support and maintain. Some users like that it is not a service and does not require yet another login to access it.

**Comment by OGNetheri** [comment]
> 

Automated raid shoutout didn't show up on raid and normal shoutout didn't trigger with chat commannd until I made the whole thing again on the web dashboard and got different key with the generate. So everythinh in the source is same as before but the auth is different. So basically the auth on the source wasn't working anymore.

**Comment by teklynk** [comment]
I see. I think the auth/access tokens expire. I have had that happen once. Not sure how to check if a token is still valid or when it expires. I will look in that and maybe display a message if it needs to be updated.

**Comment by OGNetheri** [comment]
Shoutout stopped working again. Made settings again with same settings, no help.

**Comment by OGNetheri** [comment]
I tried yet with several new oAuth's and also made one token manually through the projects main page's link. No help.

**Comment by OGNetheri** [comment]
Hopefully this project isn't dead?

**Comment by OGNetheri** [comment]
Last thing I tried made the shout out work again: I removed the "!" before "so" and that made the command work again. What is weird, I've had it always with "!" earlier.
