### ISSUE TITLE
!watchclip feature not working

### ISSUE THREAD

**Issue by RanidaeRain** [teklynk/twitch_shoutout#13]
Was trying to use the watch a clip that was posted in chat feature and its not loading the clip up at all. The rest of the features of this one seem to be working with the shoutouts but that one bit isnt. I didnt see a spot in the notes to customize the text for watching a clip in chat so not sure how to troubleshoot it.

**Comment by teklynk** [comment]
Hello,

I was not able to replicate this issue in my testing. The !watchclip only works if the URL starts with https://clips.twitch.tv/

**Comment by MsMadDuck** [comment]
!watchclip would work for the first clip posted in chat. When a new clip is posted in chat, the player will play the first clip that not the new one. Is anyone else having this issue?

**Comment by teklynk** [comment]
This is related to this issue for the clips player. https://github.com/teklynk/twitch_clips_player/issues/13

Twitch has changed the way clips are stored and we no longer have direct access to the mp4 file of the clip. This is an issue for newer clips however, older clips still work. There is a discussion here about the issue/change. https://twitch.uservoice.com/forums/310213-developers/suggestions/39228784-extend-clips-api-to-provide-the-mp4-url-so-editors

**Comment by RanidaeRain** [comment]
Is this something that is planned to be fixed? I do know about the recent
clip issue so I was aware newer clips might not work but it never worked
for me when I originally tried to implement it. I do know most of the clips
do not start with clips.twitch.tv, they start with twitch.tv/username/clip
so if they were looking for clips.twitch.tv maybe that was an older
structure before?

**Comment by teklynk** [comment]
@RanidaeRain Well, It's more than just the clips url. The issue is that we used to be able to parse the thumbnail_url from Twitch's clips API, remove the -preview-480x272.jpg and add .mp4 to it to get the clips mp4 url so that we can use it in a html video player. Twitch no longer allows access direct access to the clips mp4 with newer clips since the thumbnail_url has changed. This is discussed here: https://twitch.uservoice.com/forums/310213-developers/suggestions/39228784-extend-clips-api-to-provide-the-mp4-url-so-editors

**Comment by teklynk** [comment]
I have been looking to see how others have solved this issue. I am considering some of these solutions depending on level of effort and impact to the users. 
https://twitch.so
https://twitchat.fr

- twitch.so: Uses a php script to process and grab the new clips url. I think processor script scraps the clips web page and grabs the video src url and then redirects to it. 

- twitchat.fr: Seems to use a web page that embeds the clips iframe. I think it must also use the clips duration time to know when to close/remove the iframe? This works but it displays the Twitch player controls... play, pause, volume, fullscreen. And it doesn't allow for much customization. 

Both of these solutions are not ideal. But If they work for them, then I will give it shot too.

**Comment by teklynk** [comment]
@RanidaeRain @MsMadDuck 

This should now be fixed. There were 2 issues. One with newer clips and how they are stored. Another was the clip URL changed recently. The shoutouts and !watchclip command will now play newer clips. Please test this out and let me know if there are any issues.
