### ISSUE TITLE
showClip flag does not work.

### ISSUE THREAD

**Issue by 3laws** [teklynk/twitch_shoutout#4]
Doesn't matter if I have `showClip=true&showRecentClip=false` or `showClip=false&showRecentClip=true` web source keeps playing the same video.

I've seen it happen on several other channels, not just mine.

**Comment by teklynk** [comment]
"Show a random popular clip", showClip=true will pull a random clip based on the limit=20 value. You can increase this limit to 100 to help reduce the odds of showing the same clip. However, if a user/channel only has 3 clips, then it may show the same clip several times in a row. "Random" is like a dice roll.

I tested this with my own clips and it appears to be working as expected.  Do you happen to know which user/channel this issue happens with? I can check to see how many clips they have and see If I can reproduce the issue.
