### ISSUE TITLE
Audio doesn't match clip playing

### ISSUE THREAD

**Issue by Llucky-Llama** [teklynk/twitch_shoutout#5]
Hello! I'm new here and had your shoutout recommended to me by ArtyomHavok. I appreciate how easy it was to configure but I'm having an issue where the audio that plays isn't matching the clip that's playing. Is this a user error thing? I haven't figured how to sort it out yet. I'm in Artyom's discord as Llucky_llama if that's easiest!

Thank you in advance.

**Comment by teklynk** [comment]
Heya. I have noticed that sometimes OBS's audio monitoring will go out of sync gradually over time. Even with my OBS settings I have seen this happen. Sound alerts will occasionally do the same thing.

My OBS settings for the Shoutout Player:
- Browser source: Control audio via OBS, FPS 60, Shutdown source when not visible, Refresh browser when scene becomes active.
- Advanced Audio properties: Browser source, Audio Monitoring > Monitor and Output.

I think that the "Shutdown source when not visible", "Refresh browser when scene becomes active" will at least reset the browser source when you switch to a scene that is using it.

**Comment by Llucky-Llama** [comment]
That did the trick! Thank you so much.
I had neglected the "shutdown source when not visible" option so another scene was playing a clip simultaneously- a silly mistake for sure. TY again for helping with this!!!

**Comment by teklynk** [comment]
Glad that solved the issue!
I was originally thinking that the issue was related to OBS's audio going out of sync, since that issue has come up before. 
I will add "Shutdown source when not visible", "Refresh browser when scene becomes active" to the notes section to let others know to set those options.

-Closing issue
