### ISSUE TITLE
Shoutout browser buffering

### ISSUE THREAD

**Issue by ArakoKatoc** [teklynk/twitch_shoutout#7]
I'm not seeing the same issue manually loading the pages, my OBS stats aren't showing any binding of resources or lagged, sipped or dropped, but the video starts and stops like it's buffering on my overlay.  Hardware acceleration is on. Running obs studio 28.1.2.

**Comment by teklynk** [comment]
I suspect that this is related to the browser in OBS or hardware acceleration (though, you say that it is enabled). You can try this video test https://twitch-shoutout.pages.dev/videotest add it as a browser source and see if it also stutters/buffers.

**Comment by ArakoKatoc** [comment]
Well unfortunately this seems to be one of the most frustrating kind of problem... intermittent. Maybe it was just Twitch's backend being jank, because not only is this test source not buffering, but neither is my shoutouts, even with the exact same clips being selected. I promise, I wouldn't have reported this yesterday if it wasn't consistent, any clip over 5-ish sec was buffering but today... everything seems as smooth as it was. So thank you for the attention, if it starts creeping up again I'll give you a shout!
