### ISSUE TITLE
Multi-shout-out problem

### ISSUE THREAD

**Issue by OGNetheri** [teklynk/twitch_shoutout#9]
For some reason the multi-shoutout feat plays (and shows the chat texts) only the first 2 shoutouted streamers on multishoutout. Tried with "@" and without, same outcome.

**Comment by OGNetheri** [comment]
Correction, if there's no @ on front of streamer, there's no shoutout at all.

**Comment by teklynk** [comment]
The multi-shoutout feature should be used like:
!so @Teklynk @bigd_ihor @PeachHana @Tawejea

The @ symbol is required for each name. 

It also relies on the "Max Duration Time" setting. If it is set to 30 seconds, then it will do a shoutout every 30 seconds. 

This feature is not perfect and I plan to make it better in the future. I hope to have it use the clip duration time and not the Max Duration Time.

**Comment by OGNetheri** [comment]
Yeah, I tried with the method shown on manual and as you posted. Behaviour is like I posted, that it plays 2 shoutouts for the first two @mentions, at least third doesn't trigger the shoutout and text in chat. Haven't tried with 4 or more @mentions. And I tried @mentions after !so in different order and it's always the first 2 @menttions which trigger the shoutout.

**Comment by teklynk** [comment]
I am not able to replicate the issue. A few things to verify is:

Make sure there is a space between the @mention names: ```!so @Teklynk @bigd_ihor @PeachHana @Tawejea```. Maybe something is autofilling the @mention name and not adding a space?

If a user does not have clips, then the multishoutout will sit for the limit and not play anything until the time limit is finish, then it will move to the next user. 
This is also something that I hope to improve by first checking if clips exist, if not, then skip to the next user.

**Comment by OGNetheri** [comment]
> I am not able to replicate the issue. A few things to verify is:
> 
> Make sure there is a space between the @mention names: `!so @Teklynk @bigd_ihor @PeachHana @Tawejea`. Maybe something is autofilling the @mention name and not adding a space?
> 
> If a user does not have clips, then the multishoutout will sit for the limit and not play anything until the time limit is finish, then it will move to the next user. This is also something that I hope to improve by first checking if clips exist, if not, then skip to the next user.

I tried again and it seems it works now with the same streamers which didn't give all the shoutouts earlier and on others too with clips. Very weird as there's _no_ change on the way multishoutout is written as a command on chat. I guess this removes the issue. 🤔
